paths:

  src/migrate.py:
    service: migration-platform
    docs:
      - HLD
      - LLD
      - Migration

  src/capacity_calc.py:
    service: capacity-management
    docs:
      - HLD
      - LLD
      - Operations
