paths:

  src/migrate.py:

    service: migration-platform

    docs:
      - HLD
      - LLD

    hld: docs/08-Migrations-and-Projects/migration-platform-hld.md

    lld: docs/08-Migrations-and-Projects/migration-platform-lld.md

  src/capacity_calc.py:

    service: capacity-management

    docs:
      - HLD
      - LLD

    hld: docs/05-Operations-and-Support/03-User-Guides/capacity-management-hld.md

    lld: docs/05-Operations-and-Support/03-User-Guides/capacity-management-lld.md
